import importlib
from typing import Any

from .autonomous import (
  DeliveryConfig,
  RunOutput,
  build_state_payload,
  collect_run_output,
  deliver,
  extract_state_update,
  format_run_summary,
  load_state,
  mark_post_run_guard_failure,
  run_autonomous,
  run_autonomous_sync,
  run_output_exit_code,
  run_output_outcome,
  run_session,
  save_state,
  send_telegram,
)
from ._provider_utils import resolve_auth_config, sub_agent_default_model
from .agent_session_log import AgentSessionLog, AgentSessionRef, LogEntry, QueryCursor, resolve_agent_session_id
from .auth import (
  AuthConfig,
  AuthExpiredError,
  ChannelMismatchError,
  CredentialFailureKind,
  CredentialRefreshRequest,
  CredentialsRefreshResolver,
  CredentialsResolver,
  CredentialsTimeoutError,
  CrossUserReuseError,
  MissingUserIdError,
  NoCredentialError,
  ProviderCredentialFailure,
  ResolverResult,
)
from .code_execution import (
  BackgroundTask,
  CodeExecutionBundle,
  CodeExecutionConfig,
  DockerBackend,
  OutputRingBuffer,
  SubprocessBackend,
  build_code_execution,
  cleanup_code_execution,
  make_code_execute_status_tool_def,
  make_code_execute_tool_def,
  strip_code_execute_base64_hook,
)
from .compaction import SummaryFn, generate_and_append_summary
from .commercial_work_start import (
  COMMERCIAL_CLAIM_HEADER,
  COMMERCIAL_WORK_AUTHORIZATION_HEADER,
  CommercialWorkStartContext,
  CommercialWorkStartError,
  CommercialWorkStartFacts,
  CommercialWorkStartGate,
  PendingCommercialWorkStart,
)
from .context_builder import Message, SessionContextBuilder
from .events import (
  AggregateReadyEvent,
  AggregateReadyTrigger,
  ApprovalDecisionSource,
  ApprovalOutcome,
  ArtifactFailedEvent,
  ArtifactReadyEvent,
  ArtifactUpdatedEvent,
  ArtifactUnavailableEvent,
  DEFAULT_SCHEMA_VERSION,
  RecapApproval,
  RecapArtifact,
  RecapFailure,
  RecapVerdict,
  SessionRecapEvent,
  SkillResultCapturedEvent,  # noqa: F401 - re-exported compatibility surface
  SkillRunStartedEvent,
  SUPPORTED_SCHEMA_VERSIONS,
  ToolCallsSummary,
  ToolApprovalDecidedEvent,
  ToolApprovalRequestEvent,
  TypedRecommendationsExtractedEvent,
  event_from_dict,
  event_to_dict,
)
from .event_log import EventLog, LogEntry as EventLogEntry
from .heartbeat import HeartbeatConfig, HeartbeatLoop, TickResult, strip_heartbeat_ok
from .providers import (
  AgentSDKConfig,
  AnthropicProvider,
  CodexProvider,
  CostEstimate,
  FixtureProvider,
  ModelInfo,
  ModelProvider,
  OpenAIProvider,
  StreamEvent,
  ThinkingLevel,
  XAIProvider,
)
from .memory import EmbeddingProvider, MarkdownSyncManager, MemoryStore
from .mcp_client import McpClientManager
from .multi_user.billing import SqliteUsageLedger, SessionUsageSummary, UsageEvent, UsageLedger, UsageTotal, normalize_identity
from .package_info import (
  CONTRACTS,
  CONTRACT_AUTONOMOUS_OPERATOR_MESSAGES_V1,
  CONTRACT_CONTROL_CHAT_CONTINUATION_V1,
  CONTRACT_CREDENTIAL_REFRESH_V1,
  PACKAGE_NAME,
  SOURCE_COMMIT,
  __version__,
  package_health,
)
from .rates import ModelRates, RateTable, UnknownModelError, load_rate_table
from .retry import RetryConfig, classify_outcome, run_autonomous_with_retry
from .runner import AgentRunner, SubAgentConfig, ToolResultContext, _derive_sub_agent_id
from .send_prompt import send_prompt, send_prompt_sync
from .sdk_runner import AgentSDKRunner
from .session import AuthManager, GatewaySession, SessionStore
from .session_event_history import SessionEventHistory
from .skills import DataRequirement, SkillLoader, SkillProfile, SkillStateStore, parse_skill_file
from .thinking import EffortResolution, parse_effort, resolve_effort_pair
from .sub_agent import (
  make_get_background_result_handler,
  make_get_background_result_tool_def,
  make_send_message_handler,
  make_send_message_tool_def,
  make_resume_handler,
  make_resume_tool_def,
  make_run_agent_handler,
  make_run_agent_tool_def,
)
from .task_registry import (
  COORDINATOR_DEFAULT_PREAMBLE,
  CoordinatorConfig,
  make_progress_tracker,
  NotificationQueue,
  ParentMessage,
  ProviderResolver,
  ResolvedProvider,
  TaskEntry,
  TaskLifecycleListener,
  TaskNotification,
  TaskProgress,
  TaskRegistry,
  TaskState,
)
from .tool_dispatcher import (
  ApprovalDecision,
  ApprovalRequest,
  InterceptContext,
  InterceptDecision,
  InterceptResult,
  RELAY_POLICY_DENIED_MESSAGE,
  RELAY_POLICY_DENIED_SUB_CODE,
  ToolDispatcher,
  ToolExecutionContext,
  ToolInterceptor,
  ToolResult,
  TransportApprovalRequest,
  TransportApprovalResult,
  resolve_denied_provenance,
)
from .approval_policy import (
  ApprovalConstraint,
  ApprovalConstraintError,
  ApprovalDecision as PolicyApprovalDecision,
  ApprovalPolicy,
  ApprovalRequest as PolicyApprovalRequest,
  ApprovalRequestPayload,
  ApprovalVote,
  PersistentGrant,
  RunContext,
)

_LAZY_EXPORTS = {
  "ChatRuntime": ("agent_gateway.server", "ChatRuntime"),
  "ChatTurnInputs": ("agent_gateway.server", "ChatTurnInputs"),
  "ChatTurnResult": ("agent_gateway.server", "ChatTurnResult"),
  "GatewayServerConfig": ("agent_gateway.server", "GatewayServerConfig"),
  "ModelCatalog": ("agent_gateway.server", "ModelCatalog"),
  "RequestContext": ("agent_gateway.server", "RequestContext"),
  "create_agent": ("agent_gateway.easy", "create_agent"),
  "create_gateway_app": ("agent_gateway.server", "create_gateway_app"),
}


def __getattr__(name: str) -> Any:
  try:
    module_name, attr_name = _LAZY_EXPORTS[name]
  except KeyError as exc:
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
  value = getattr(importlib.import_module(module_name), attr_name)
  globals()[name] = value
  return value


__all__ = [
  "AgentSDKConfig",
  "AgentRunner",
  "AgentSDKRunner",
  "AgentSessionLog",
  "AgentSessionRef",
  "AggregateReadyEvent",
  "AggregateReadyTrigger",
  "ApprovalDecision",
  "ApprovalDecisionSource",
  "ApprovalConstraint",
  "ApprovalConstraintError",
  "ApprovalOutcome",
  "ApprovalPolicy",
  "ApprovalRequestPayload",
  "ApprovalRequest",
  "ApprovalVote",
  "AnthropicProvider",
  "ArtifactFailedEvent",
  "ArtifactReadyEvent",
  "ArtifactUpdatedEvent",
  "ArtifactUnavailableEvent",
  "AuthConfig",
  "AuthManager",
  "AuthExpiredError",
  "ChannelMismatchError",
  "BackgroundTask",
  "CONTRACTS",
  "CONTRACT_AUTONOMOUS_OPERATOR_MESSAGES_V1",
  "CONTRACT_CONTROL_CHAT_CONTINUATION_V1",
  "CONTRACT_CREDENTIAL_REFRESH_V1",
  "CodexProvider",
  "COMMERCIAL_CLAIM_HEADER",
  "COMMERCIAL_WORK_AUTHORIZATION_HEADER",
  "CommercialWorkStartContext",
  "CommercialWorkStartError",
  "CommercialWorkStartFacts",
  "CommercialWorkStartGate",
  "COORDINATOR_DEFAULT_PREAMBLE",
  "CoordinatorConfig",
  "CostEstimate",
  "CredentialFailureKind",
  "CredentialRefreshRequest",
  "CredentialsRefreshResolver",
  "CredentialsResolver",
  "CredentialsTimeoutError",
  "CrossUserReuseError",
  "ChatRuntime",
  "ChatTurnInputs",
  "ChatTurnResult",
  "CodeExecutionBundle",
  "CodeExecutionConfig",
  "Message",
  "DeliveryConfig",
  "DEFAULT_SCHEMA_VERSION",
  "DataRequirement",
  "DockerBackend",
  "EventLog",
  "EventLogEntry",
  "EffortResolution",
  "FixtureProvider",
  "GatewaySession",
  "GatewayServerConfig",
  "HeartbeatConfig",
  "HeartbeatLoop",
  "InterceptContext",
  "InterceptDecision",
  "InterceptResult",
  "LogEntry",
  "MarkdownSyncManager",
  "MemoryStore",
  "McpClientManager",
  "MissingUserIdError",
  "ModelCatalog",
  "ModelRates",
  "ModelInfo",
  "ModelProvider",
  "NoCredentialError",
  "NotificationQueue",
  "OpenAIProvider",
  "OutputRingBuffer",
  "XAIProvider",
  "PACKAGE_NAME",
  "ProviderCredentialFailure",
  "parse_effort",
  "resolve_effort_pair",
  "ProviderResolver",
  "QueryCursor",
  "RELAY_POLICY_DENIED_MESSAGE",
  "RELAY_POLICY_DENIED_SUB_CODE",
  "RecapApproval",
  "RecapArtifact",
  "RecapFailure",
  "RecapVerdict",
  "RateTable",
  "RequestContext",
  "PersistentGrant",
  "PolicyApprovalDecision",
  "PolicyApprovalRequest",
  "PendingCommercialWorkStart",
  "ResolverResult",
  "SOURCE_COMMIT",
  "sub_agent_default_model",
  "ResolvedProvider",
  "RetryConfig",
  "RunOutput",
  "resolve_agent_session_id",
  "resolve_auth_config",
  "send_prompt",
  "send_prompt_sync",
  "SessionRecapEvent",
  "SessionUsageSummary",
  "SessionContextBuilder",
  "SessionEventHistory",
  "SessionStore",
  "SkillLoader",
  "SkillProfile",
  "SkillStateStore",
  "SkillRunStartedEvent",
  "StreamEvent",
  "SUPPORTED_SCHEMA_VERSIONS",
  "SubAgentConfig",
  "SubprocessBackend",
  "SummaryFn",
  "SqliteUsageLedger",
  "EmbeddingProvider",
  "ThinkingLevel",
  "TickResult",
  "ParentMessage",
  "TaskEntry",
  "TaskLifecycleListener",
  "TaskNotification",
  "TaskProgress",
  "TaskRegistry",
  "TaskState",
  "ToolDispatcher",
  "ToolCallsSummary",
  "ToolApprovalDecidedEvent",
  "ToolApprovalRequestEvent",
  "ToolExecutionContext",
  "ToolInterceptor",
  "ToolResult",
  "TypedRecommendationsExtractedEvent",
  "TransportApprovalRequest",
  "TransportApprovalResult",
  "resolve_denied_provenance",
  "RunContext",
  "ToolResultContext",
  "UsageEvent",
  "UsageLedger",
  "UsageTotal",
  "__version__",
  "normalize_identity",
  "UnknownModelError",
  "build_state_payload",
  "build_code_execution",
  "collect_run_output",
  "cleanup_code_execution",
  "classify_outcome",
  "create_agent",
  "create_gateway_app",
  "deliver",
  "event_from_dict",
  "event_to_dict",
  "_derive_sub_agent_id",
  "extract_state_update",
  "format_run_summary",
  "generate_and_append_summary",
  "load_state",
  "load_rate_table",
  "mark_post_run_guard_failure",
  "package_health",
  "make_code_execute_status_tool_def",
  "make_code_execute_tool_def",
  "make_get_background_result_handler",
  "make_get_background_result_tool_def",
  "make_send_message_handler",
  "make_send_message_tool_def",
  "make_resume_handler",
  "make_resume_tool_def",
  "make_progress_tracker",
  "make_run_agent_handler",
  "make_run_agent_tool_def",
  "parse_skill_file",
  "run_autonomous",
  "run_autonomous_with_retry",
  "run_autonomous_sync",
  "run_output_exit_code",
  "run_output_outcome",
  "run_session",
  "save_state",
  "send_telegram",
  "strip_code_execute_base64_hook",
  "strip_heartbeat_ok",
]
