import importlib
from typing import Any

from .autonomous import (
  DeliveryConfig,
  RunOutput,
  build_state_payload,
  collect_run_output,
  deliver,
  extract_state_update,
  format_run_summary,
  load_state,
  mark_post_run_guard_failure,
  run_autonomous,
  run_autonomous_sync,
  run_output_exit_code,
  run_output_outcome,
  run_session,
  save_state,
  send_telegram,
)
from .autonomous_capability_handoff import (
  AutonomousCapabilityBinding,
  AutonomousCapabilityBindingRequest,
  AutonomousCapabilityBindingResolver,
  AutonomousCapabilityBindingSource,
  resolve_autonomous_capability_binding,
)
from .autonomous_launch_envelope import (
  AUTONOMOUS_CAPABILITY_ENVELOPE_AUDIENCE,
  AUTONOMOUS_CAPABILITY_ENVELOPE_CLOCK_SKEW_SECONDS,
  AUTONOMOUS_CAPABILITY_ENVELOPE_ENV,
  AUTONOMOUS_CAPABILITY_ENVELOPE_MAX_TTL_SECONDS,
  AUTONOMOUS_CAPABILITY_ENVELOPE_TTL_SECONDS,
  AUTONOMOUS_CAPABILITY_ENVELOPE_VERSION,
  AUTONOMOUS_TASK_ID_ENV,
  AutonomousLaunchEnvelope,
  sign_autonomous_launch_envelope,
  verify_autonomous_launch_envelope,
)
from ._provider_utils import resolve_auth_config
from .agent_session_log import (
  AgentSessionLog,
  AgentSessionRef,
  IdempotentEventConflictError,
  LogEntry,
  QueryCursor,
  resolve_agent_session_id,
)
from .retention import (
  FileAgeAdapter,
  KeepForeverAdapter,
  RetentionAdapter,
  RetentionCatalog,
  RetentionCatalogEntry,
  RetentionPolicy,
  RetentionSweepContext,
  RetentionSweepReport,
  RetentionSweeper,
)
from .auth import (
  AuthConfig,
  AuthExpiredError,
  ChannelMismatchError,
  CredentialFailureKind,
  CredentialRefreshRequest,
  CredentialsRefreshResolver,
  CredentialsResolver,
  CredentialsTimeoutError,
  CrossUserReuseError,
  MissingUserIdError,
  NoCredentialError,
  ProviderCredentialFailure,
  ResolverResult,
)
from .capability_binding import (
  CAPABILITY_IDS,
  AuthContext,
  CapabilityBind,
  CapabilityId,
  CapabilityResolutionCode,
  CapabilityResolutionError,
  CredentialHandle,
  CredentialPrincipal,
  EligibleModelChoice,
  ModelSelectionIntent,
  RunMode,
  eligible_model_choices,
  reauthorize_capability_bind,
  resolve_capability_model,
  validate_reported_identity,
)
from .capability_execution import (
  BoundCapabilityExecution,
  CapabilityAdapterResolver,
  CapabilityExecutionResolver,
  CredentialMaterializer,
  MaterializedCredential,
)
from .model_registry import (
  CAPABILITY_EXECUTION_PROCESS,
  EXTERNALLY_EXECUTED_CAPABILITY_IDS,
  GATEWAY_EXECUTED_CAPABILITY_IDS,
  INITIAL_MODEL_REGISTRY,
  INITIAL_MODEL_SELECTION_POLICY,
  AdapterRouteSupport,
  CapabilityDefault,
  CapabilitySelectionPolicy,
  ModelRegistryEntry,
  ProductModelRegistry,
  ProductModelSelectionPolicy,
)
from .model_preferences import ModelPreferenceStore
from .code_execution import (
  BackgroundTask,
  CodeExecutionBundle,
  CodeExecutionConfig,
  DockerBackend,
  OutputRingBuffer,
  SubprocessBackend,
  build_code_execution,
  cleanup_code_execution,
  make_code_execute_status_tool_def,
  make_code_execute_tool_def,
  strip_code_execute_base64_hook,
)
from .compaction import SummaryFn, generate_and_append_summary
from .commercial_work_start import (
  COMMERCIAL_CLAIM_HEADER,
  COMMERCIAL_WORK_AUTHORIZATION_HEADER,
  CommercialWorkStartContext,
  CommercialWorkStartError,
  CommercialWorkStartFacts,
  CommercialWorkStartGate,
  PendingCommercialWorkStart,
)
from .context_builder import Message, SessionContextBuilder
from .events import (
  AggregateReadyEvent,
  AggregateReadyTrigger,
  ApprovalDecisionSource,
  ApprovalOutcome,
  ArtifactFailedEvent,
  ArtifactReadyEvent,
  ArtifactUpdatedEvent,
  ArtifactUnavailableEvent,
  DEFAULT_SCHEMA_VERSION,
  RecapApproval,
  RecapArtifact,
  RecapFailure,
  RecapVerdict,
  SessionRecapEvent,
  SkillResultCapturedEvent,  # noqa: F401 - re-exported compatibility surface
  SkillRunStartedEvent,
  SUPPORTED_SCHEMA_VERSIONS,
  ToolCallsSummary,
  ToolApprovalDecidedEvent,
  ToolApprovalRequestEvent,
  TypedRecommendationsExtractedEvent,
  event_from_dict,
  event_to_dict,
)
from .event_log import EventLog, LogEntry as EventLogEntry
from .heartbeat import HeartbeatConfig, HeartbeatLoop, TickResult, strip_heartbeat_ok
from .providers import (
  AgentSDKConfig,
  AnthropicProvider,
  CodexProvider,
  CostEstimate,
  ModelInfo,
  ModelProvider,
  OpenAIProvider,
  StreamEvent,
  ThinkingLevel,
  XAIProvider,
  installed_adapter_route_support,
)

# Import-time admission of the loaded INITIAL artifacts against the adapter
# support the installed package actually declares, for the capabilities this
# (gateway) process executes.  Externally-executed capabilities (risk.*,
# investment.*) are admitted registry facts resolved in their own serving
# processes.  `create_gateway_app` re-runs the full closure over whatever
# registry the server is configured with.
INITIAL_MODEL_REGISTRY.admit_adapter_support(
  installed_adapter_route_support(),
  executed_capability_ids=GATEWAY_EXECUTED_CAPABILITY_IDS,
)
from .memory import EmbeddingProvider, MarkdownSyncManager, MemoryStore
from .mcp_client import McpClientManager
from .multi_user.billing import SqliteUsageLedger, SessionUsageSummary, UsageEvent, UsageLedger, UsageTotal, normalize_identity
from .package_info import (
  CONTRACTS,
  CONTRACT_AUTONOMOUS_OPERATOR_MESSAGES_V1,
  CONTRACT_CHAT_ATTACHMENTS_V1,
  CONTRACT_CONTROL_CHAT_CONTINUATION_V1,
  CONTRACT_CONTROL_RUN_V1,
  CONTRACT_CREDENTIAL_REFRESH_V1,
  PACKAGE_NAME,
  SOURCE_COMMIT,
  __version__,
  package_health,
)
from .rates import ModelRates, RateTable, UnknownModelError, load_rate_table
from .retry import RetryConfig, classify_outcome, run_autonomous_with_retry
from .run_identity import (
  MODEL_RUN_IDENTITY_FORBIDDEN_TOOLS,
  MODEL_RUN_IDENTITY_LOCAL_TOOLS,
  MODEL_RUN_IDENTITY_MCP_TOOLS,
  RUN_IDENTITY_MCP_ENV,
  RUN_IDENTITY_MAX_LENGTH,
  RUN_IDENTITY_MCP_TOOLS_ENV,
  RunIdentityCarrier,
  RunIdentityCarrierError,
  inject_run_identity_into_mcp_server_configs,
  model_run_identity_for_tool,
  validate_run_identity,
)
from .runner import AgentRunner, SubAgentConfig, ToolResultContext, _derive_sub_agent_id
from .runner_background_tasks import WorkflowTaskMetadata
from .send_prompt import send_prompt, send_prompt_sync
from .sdk_runner import AgentSDKRunner
from .session import (
  AuthManager,
  GatewaySession,
  SessionStore,
  attach_session_credential_handle,
  bind_session_credentials,
)
from .session_event_history import SessionEventHistory
from .skills import SkillLoader, SkillProfile, SkillStateStore, parse_skill_file
from .thinking import EffortResolution, parse_effort, resolve_effort_pair
from .sub_agent import (
  make_get_background_result_handler,
  make_get_background_result_tool_def,
  make_send_message_handler,
  make_send_message_tool_def,
  make_resume_handler,
  make_resume_tool_def,
  make_run_agent_handler,
  make_run_agent_tool_def,
)
from .task_registry import (
  COORDINATOR_DEFAULT_PREAMBLE,
  CoordinatorConfig,
  make_progress_tracker,
  NotificationQueue,
  ParentMessage,
  TaskEntry,
  TaskLifecycleListener,
  TaskNotification,
  TaskProgress,
  TaskRegistry,
  TaskState,
)
from .tool_dispatcher import (
  ApprovalDecision,
  ApprovalRequest,
  InterceptContext,
  InterceptDecision,
  InterceptResult,
  ToolDispatcher,
  ToolExecutionContext,
  ToolInterceptor,
  ToolResult,
  TransportApprovalRequest,
  TransportApprovalResult,
)
from .dispatcher_factory import (
  DispatcherConstructionError,
  GatewayDispatcherDeps,
  InvocationPrincipal,
  build_tool_dispatcher,
)
from .approval_policy import (
  ApprovalConstraint,
  ApprovalConstraintError,
  ApprovalDecision as PolicyApprovalDecision,
  ApprovalPolicy,
  ApprovalRequest as PolicyApprovalRequest,
  ApprovalRequestPayload,
  ApprovalVote,
  PersistentGrant,
  RunContext,
)

_LAZY_EXPORTS = {
  "ChatRuntime": ("agent_gateway.server", "ChatRuntime"),
  "ChatTurnInputs": ("agent_gateway.server", "ChatTurnInputs"),
  "ChatTurnResult": ("agent_gateway.server", "ChatTurnResult"),
  "GatewayServerConfig": ("agent_gateway.server", "GatewayServerConfig"),
  "RequestContext": ("agent_gateway.server", "RequestContext"),
  "SessionExecutionPolicy": (
    "agent_gateway.server_models",
    "SessionExecutionPolicy",
  ),
  "create_agent": ("agent_gateway.easy", "create_agent"),
  "create_gateway_app": ("agent_gateway.server", "create_gateway_app"),
}


def __getattr__(name: str) -> Any:
  try:
    module_name, attr_name = _LAZY_EXPORTS[name]
  except KeyError as exc:
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
  value = getattr(importlib.import_module(module_name), attr_name)
  globals()[name] = value
  return value


__all__ = [
  "FileAgeAdapter",
  "KeepForeverAdapter",
  "RetentionAdapter",
  "RetentionCatalog",
  "RetentionCatalogEntry",
  "RetentionPolicy",
  "RetentionSweepContext",
  "RetentionSweepReport",
  "RetentionSweeper",
  "AgentSDKConfig",
  "AgentRunner",
  "AgentSDKRunner",
  "AgentSessionLog",
  "IdempotentEventConflictError",
  "AgentSessionRef",
  "AggregateReadyEvent",
  "AggregateReadyTrigger",
  "ApprovalDecision",
  "ApprovalDecisionSource",
  "ApprovalConstraint",
  "ApprovalConstraintError",
  "ApprovalOutcome",
  "ApprovalPolicy",
  "ApprovalRequestPayload",
  "ApprovalRequest",
  "ApprovalVote",
  "AnthropicProvider",
  "AUTONOMOUS_CAPABILITY_ENVELOPE_AUDIENCE",
  "AUTONOMOUS_CAPABILITY_ENVELOPE_CLOCK_SKEW_SECONDS",
  "AUTONOMOUS_CAPABILITY_ENVELOPE_ENV",
  "AUTONOMOUS_CAPABILITY_ENVELOPE_MAX_TTL_SECONDS",
  "AUTONOMOUS_CAPABILITY_ENVELOPE_TTL_SECONDS",
  "AUTONOMOUS_CAPABILITY_ENVELOPE_VERSION",
  "AUTONOMOUS_TASK_ID_ENV",
  "ArtifactFailedEvent",
  "ArtifactReadyEvent",
  "ArtifactUpdatedEvent",
  "ArtifactUnavailableEvent",
  "AuthConfig",
  "AuthContext",
  "AuthManager",
  "AuthExpiredError",
  "AutonomousCapabilityBinding",
  "AutonomousCapabilityBindingRequest",
  "AutonomousCapabilityBindingResolver",
  "AutonomousCapabilityBindingSource",
  "AutonomousLaunchEnvelope",
  "ChannelMismatchError",
  "BackgroundTask",
  "CONTRACTS",
  "CONTRACT_AUTONOMOUS_OPERATOR_MESSAGES_V1",
  "CONTRACT_CHAT_ATTACHMENTS_V1",
  "CONTRACT_CONTROL_CHAT_CONTINUATION_V1",
  "CONTRACT_CONTROL_RUN_V1",
  "CONTRACT_CREDENTIAL_REFRESH_V1",
  "CodexProvider",
  "COMMERCIAL_CLAIM_HEADER",
  "COMMERCIAL_WORK_AUTHORIZATION_HEADER",
  "CommercialWorkStartContext",
  "CommercialWorkStartError",
  "CommercialWorkStartFacts",
  "CommercialWorkStartGate",
  "COORDINATOR_DEFAULT_PREAMBLE",
  "CoordinatorConfig",
  "CostEstimate",
  "CAPABILITY_IDS",
  "BoundCapabilityExecution",
  "CapabilityBind",
  "CapabilityAdapterResolver",
  "CapabilityExecutionResolver",
  "CapabilityId",
  "CapabilityResolutionCode",
  "CapabilityResolutionError",
  "CredentialFailureKind",
  "CredentialHandle",
  "CredentialMaterializer",
  "CredentialPrincipal",
  "CredentialRefreshRequest",
  "CredentialsRefreshResolver",
  "CredentialsResolver",
  "CredentialsTimeoutError",
  "CrossUserReuseError",
  "ChatRuntime",
  "ChatTurnInputs",
  "ChatTurnResult",
  "CodeExecutionBundle",
  "CodeExecutionConfig",
  "Message",
  "DeliveryConfig",
  "DispatcherConstructionError",
  "DEFAULT_SCHEMA_VERSION",
  "DockerBackend",
  "EventLog",
  "EventLogEntry",
  "EffortResolution",
  "GatewaySession",
  "GatewayDispatcherDeps",
  "GatewayServerConfig",
  "HeartbeatConfig",
  "HeartbeatLoop",
  "InterceptContext",
  "InterceptDecision",
  "InterceptResult",
  "InvocationPrincipal",
  "LogEntry",
  "MarkdownSyncManager",
  "MemoryStore",
  "McpClientManager",
  "MissingUserIdError",
  "EligibleModelChoice",
  "CAPABILITY_EXECUTION_PROCESS",
  "EXTERNALLY_EXECUTED_CAPABILITY_IDS",
  "GATEWAY_EXECUTED_CAPABILITY_IDS",
  "INITIAL_MODEL_REGISTRY",
  "INITIAL_MODEL_SELECTION_POLICY",
  "AdapterRouteSupport",
  "installed_adapter_route_support",
  "CapabilityDefault",
  "CapabilitySelectionPolicy",
  "ModelRegistryEntry",
  "ProductModelRegistry",
  "ProductModelSelectionPolicy",
  "ModelRates",
  "ModelInfo",
  "ModelProvider",
  "ModelSelectionIntent",
  "ModelPreferenceStore",
  "MaterializedCredential",
  "NoCredentialError",
  "NotificationQueue",
  "OpenAIProvider",
  "OutputRingBuffer",
  "XAIProvider",
  "PACKAGE_NAME",
  "ProviderCredentialFailure",
  "parse_effort",
  "resolve_effort_pair",
  "QueryCursor",
  "RecapApproval",
  "RecapArtifact",
  "RecapFailure",
  "RecapVerdict",
  "RateTable",
  "RequestContext",
  "SessionExecutionPolicy",
  "PersistentGrant",
  "PolicyApprovalDecision",
  "PolicyApprovalRequest",
  "PendingCommercialWorkStart",
  "ResolverResult",
  "SOURCE_COMMIT",
  "RetryConfig",
  "RunOutput",
  "RunMode",
  "RunIdentityCarrier",
  "RunIdentityCarrierError",
  "RUN_IDENTITY_MCP_ENV",
  "RUN_IDENTITY_MAX_LENGTH",
  "RUN_IDENTITY_MCP_TOOLS_ENV",
  "MODEL_RUN_IDENTITY_FORBIDDEN_TOOLS",
  "MODEL_RUN_IDENTITY_LOCAL_TOOLS",
  "MODEL_RUN_IDENTITY_MCP_TOOLS",
  "resolve_agent_session_id",
  "resolve_auth_config",
  "resolve_capability_model",
  "eligible_model_choices",
  "reauthorize_capability_bind",
  "validate_reported_identity",
  "resolve_autonomous_capability_binding",
  "send_prompt",
  "send_prompt_sync",
  "SessionRecapEvent",
  "SessionUsageSummary",
  "SessionContextBuilder",
  "SessionEventHistory",
  "SessionStore",
  "SkillLoader",
  "SkillProfile",
  "SkillStateStore",
  "SkillRunStartedEvent",
  "StreamEvent",
  "SUPPORTED_SCHEMA_VERSIONS",
  "SubAgentConfig",
  "SubprocessBackend",
  "SummaryFn",
  "SqliteUsageLedger",
  "EmbeddingProvider",
  "ThinkingLevel",
  "TickResult",
  "ParentMessage",
  "TaskEntry",
  "TaskLifecycleListener",
  "TaskNotification",
  "TaskProgress",
  "TaskRegistry",
  "TaskState",
  "WorkflowTaskMetadata",
  "ToolDispatcher",
  "ToolCallsSummary",
  "ToolApprovalDecidedEvent",
  "ToolApprovalRequestEvent",
  "ToolExecutionContext",
  "ToolInterceptor",
  "ToolResult",
  "TypedRecommendationsExtractedEvent",
  "TransportApprovalRequest",
  "TransportApprovalResult",
  "RunContext",
  "ToolResultContext",
  "UsageEvent",
  "UsageLedger",
  "UsageTotal",
  "__version__",
  "normalize_identity",
  "inject_run_identity_into_mcp_server_configs",
  "model_run_identity_for_tool",
  "validate_run_identity",
  "UnknownModelError",
  "build_state_payload",
  "bind_session_credentials",
  "attach_session_credential_handle",
  "build_code_execution",
  "build_tool_dispatcher",
  "collect_run_output",
  "cleanup_code_execution",
  "classify_outcome",
  "create_agent",
  "create_gateway_app",
  "deliver",
  "event_from_dict",
  "event_to_dict",
  "_derive_sub_agent_id",
  "extract_state_update",
  "format_run_summary",
  "generate_and_append_summary",
  "load_state",
  "load_rate_table",
  "mark_post_run_guard_failure",
  "package_health",
  "make_code_execute_status_tool_def",
  "make_code_execute_tool_def",
  "make_get_background_result_handler",
  "make_get_background_result_tool_def",
  "make_send_message_handler",
  "make_send_message_tool_def",
  "make_resume_handler",
  "make_resume_tool_def",
  "make_progress_tracker",
  "make_run_agent_handler",
  "make_run_agent_tool_def",
  "parse_skill_file",
  "run_autonomous",
  "run_autonomous_with_retry",
  "run_autonomous_sync",
  "run_output_exit_code",
  "run_output_outcome",
  "run_session",
  "save_state",
  "send_telegram",
  "sign_autonomous_launch_envelope",
  "strip_code_execute_base64_hook",
  "strip_heartbeat_ok",
  "verify_autonomous_launch_envelope",
]
